export enum AppRoutes {
  HOME = '/home',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  VERIFY_ACCOUNT = '/verify-account',
  FORGOT_PASSWORD = '/forgot-password',
  SET_PASSWORD = '/set-password',
  FILE_UPLOAD = '/file-upload',
  PROJECT_HOME = '/project-home',
  PROJECT_MAIN = '/project-main',
  ORGANIZATION_MAIN = '/organization-main',
  VIEW_SOURCE = '/view-source',
  IMPORT_PAGE = '/import-page',
  SAVE_PAGE = '/save-page',
  SYNC_PAGE = '/sync-page',
  UNSYNC_PAGE = '/unsync-page',
  DELETE_DIALOG = '/delete-dialog',
  EXIST_DIALOG = '/exist-dialog',
  PROJECT_CREATE = '/create-project',
  PROJECT_EXIST = '/existing-project',
  VERSION_HISTORY = '/version-history',
  ADD_VERSION = '/add-version',
}
